<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'sku' => 'HK-2MP-BULLET',
                'name' => 'Hikvision 2 MP Bullet Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2CE16D0T-IRPF',
                'description' => '2 MP outdoor IR bullet CCTV camera (20m IR, IP67 weatherproof)',
                'unit' => 'Nos',
                'cost_price' => 1350,
                'unit_price' => 2200,
                'stock_quantity' => 45,
                'min_stock_alert' => 10,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'HK-4MP-BULLET',
                'name' => 'Hikvision 4 MP Bullet Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2CD1043G0-I',
                'description' => '4 MP outdoor IR bullet IP CCTV camera with PoE support',
                'unit' => 'Nos',
                'cost_price' => 2100,
                'unit_price' => 3500,
                'stock_quantity' => 38,
                'min_stock_alert' => 10,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'HK-4MP-DOME',
                'name' => 'Hikvision 4 MP Dome Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2CD1143G0-I',
                'description' => '4 MP indoor vandal-resistant dome CCTV camera with IR',
                'unit' => 'Nos',
                'cost_price' => 2200,
                'unit_price' => 3600,
                'stock_quantity' => 40,
                'min_stock_alert' => 10,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'DAH-4MP-IP-BULLET',
                'name' => 'Dahua 4 MP IP Bullet Camera',
                'category' => 'Camera',
                'brand' => 'Dahua',
                'model_no' => 'DH-IPC-HFW1431S',
                'description' => '4 MP IP bullet camera with IR night vision and smart codec',
                'unit' => 'Nos',
                'cost_price' => 2050,
                'unit_price' => 3400,
                'stock_quantity' => 30,
                'min_stock_alert' => 8,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'HK-5MP-COLORVU',
                'name' => 'Hikvision 5 MP ColorVu Bullet Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2CE12HFT-F',
                'description' => '5 MP 24/7 full-color night-vision CCTV bullet camera with F1.0 aperture',
                'unit' => 'Nos',
                'cost_price' => 3100,
                'unit_price' => 5200,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'HK-2MP-PTZ',
                'name' => 'Hikvision 2 MP PTZ Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2DE4225IW-DE',
                'description' => '2 MP PTZ speed dome camera with 25x optical zoom and 100m IR',
                'unit' => 'Nos',
                'cost_price' => 11500,
                'unit_price' => 18000,
                'stock_quantity' => 8,
                'min_stock_alert' => 2,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'HK-4MP-WIFI',
                'name' => 'Hikvision 4 MP Wi-Fi Camera',
                'category' => 'Camera',
                'brand' => 'Hikvision',
                'model_no' => 'DS-2CV2Q41FD-IW',
                'description' => '4 MP Wi-Fi indoor pan-tilt camera with two-way audio and mobile monitoring',
                'unit' => 'Nos',
                'cost_price' => 2400,
                'unit_price' => 3900,
                'stock_quantity' => 20,
                'min_stock_alert' => 5,
                'hsn_code' => '85258900',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'DVR-4CH',
                'name' => '4 Channel DVR',
                'category' => 'Recorder',
                'brand' => 'Hikvision',
                'model_no' => 'iDS-7204HQHI-M1/S',
                'description' => '4 channel AcuSense DVR for analog HD CCTV cameras',
                'unit' => 'Nos',
                'cost_price' => 2600,
                'unit_price' => 4200,
                'stock_quantity' => 15,
                'min_stock_alert' => 3,
                'hsn_code' => '85219090',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'DVR-8CH',
                'name' => '8 Channel DVR',
                'category' => 'Recorder',
                'brand' => 'Hikvision',
                'model_no' => 'iDS-7208HQHI-M1/S',
                'description' => '8 channel AcuSense DVR for analog HD CCTV cameras',
                'unit' => 'Nos',
                'cost_price' => 4100,
                'unit_price' => 6500,
                'stock_quantity' => 18,
                'min_stock_alert' => 4,
                'hsn_code' => '85219090',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'NVR-8CH',
                'name' => '8 Channel NVR',
                'category' => 'Recorder',
                'brand' => 'Hikvision',
                'model_no' => 'DS-7608NI-Q1/8P',
                'description' => '8 channel 4K network video recorder with 8 built-in PoE ports',
                'unit' => 'Nos',
                'cost_price' => 5300,
                'unit_price' => 8500,
                'stock_quantity' => 14,
                'min_stock_alert' => 3,
                'hsn_code' => '85219090',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'NVR-16CH',
                'name' => '16 Channel NVR',
                'category' => 'Recorder',
                'brand' => 'Hikvision',
                'model_no' => 'DS-7716NI-I4',
                'description' => '16 channel 4K professional NVR with 4 SATA bays and H.265+',
                'unit' => 'Nos',
                'cost_price' => 7900,
                'unit_price' => 12500,
                'stock_quantity' => 10,
                'min_stock_alert' => 2,
                'hsn_code' => '85219090',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'NVR-32CH',
                'name' => '32 Channel NVR',
                'category' => 'Recorder',
                'brand' => 'Hikvision',
                'model_no' => 'DS-7732NI-I4/16P',
                'description' => '32 channel enterprise NVR for large IP camera installations with RAID support',
                'unit' => 'Nos',
                'cost_price' => 15500,
                'unit_price' => 24000,
                'stock_quantity' => 6,
                'min_stock_alert' => 1,
                'hsn_code' => '85219090',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'HDD-SURV-1TB',
                'name' => '1 TB Surveillance Hard Disk',
                'category' => 'Storage',
                'brand' => 'Seagate',
                'model_no' => 'ST1000VX005 (SkyHawk)',
                'description' => '1 TB 24x7 surveillance hard disk with AllFrame streaming',
                'unit' => 'Nos',
                'cost_price' => 3200,
                'unit_price' => 4800,
                'stock_quantity' => 22,
                'min_stock_alert' => 5,
                'hsn_code' => '84717020',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'HDD-SURV-2TB',
                'name' => '2 TB Surveillance Hard Disk',
                'category' => 'Storage',
                'brand' => 'Western Digital',
                'model_no' => 'WD20PURZ (WD Purple)',
                'description' => '2 TB WD Purple 24/7 surveillance hard disk',
                'unit' => 'Nos',
                'cost_price' => 4300,
                'unit_price' => 6500,
                'stock_quantity' => 28,
                'min_stock_alert' => 6,
                'hsn_code' => '84717020',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'HDD-SURV-4TB',
                'name' => '4 TB Surveillance Hard Disk',
                'category' => 'Storage',
                'brand' => 'Western Digital',
                'model_no' => 'WD40PURZ (WD Purple)',
                'description' => '4 TB WD Purple surveillance drive engineered for NVR systems',
                'unit' => 'Nos',
                'cost_price' => 6800,
                'unit_price' => 9800,
                'stock_quantity' => 20,
                'min_stock_alert' => 4,
                'hsn_code' => '84717020',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'HDD-SURV-6TB',
                'name' => '6 TB Surveillance Hard Disk',
                'category' => 'Storage',
                'brand' => 'Western Digital',
                'model_no' => 'WD60PURZ (WD Purple)',
                'description' => '6 TB high capacity surveillance hard drive',
                'unit' => 'Nos',
                'cost_price' => 10200,
                'unit_price' => 14500,
                'stock_quantity' => 12,
                'min_stock_alert' => 2,
                'hsn_code' => '84717020',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'POE-8PORT',
                'name' => '8 Port PoE Switch',
                'category' => 'Networking',
                'brand' => 'Hikvision',
                'model_no' => 'DS-3E0109P-E/M',
                'description' => '8 port Fast Ethernet unmanaged PoE switch (65W budget)',
                'unit' => 'Nos',
                'cost_price' => 3500,
                'unit_price' => 5500,
                'stock_quantity' => 16,
                'min_stock_alert' => 4,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'POE-16PORT',
                'name' => '16 Port PoE Switch',
                'category' => 'Networking',
                'brand' => 'Hikvision',
                'model_no' => 'DS-3E0318P-E/M',
                'description' => '16 port PoE switch with 2 Gigabit Combo uplink ports (130W budget)',
                'unit' => 'Nos',
                'cost_price' => 6800,
                'unit_price' => 10500,
                'stock_quantity' => 12,
                'min_stock_alert' => 3,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'POE-24PORT-GIG',
                'name' => '24 Port Gigabit PoE Switch',
                'category' => 'Networking',
                'brand' => 'Hikvision',
                'model_no' => 'DS-3E1526P-SI',
                'description' => '24 port smart managed gigabit PoE switch with SFP slots (370W budget)',
                'unit' => 'Nos',
                'cost_price' => 12200,
                'unit_price' => 18500,
                'stock_quantity' => 7,
                'min_stock_alert' => 2,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'TPLINK-SW-8G',
                'name' => 'TP-Link 8 Port Gigabit Switch',
                'category' => 'Networking',
                'brand' => 'TP-Link',
                'model_no' => 'TL-SG108',
                'description' => '8 port unmanaged desktop gigabit LAN switch with metal casing',
                'unit' => 'Nos',
                'cost_price' => 1550,
                'unit_price' => 2400,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'TPLINK-ROUTER-GIG',
                'name' => 'TP-Link Gigabit Router',
                'category' => 'Networking',
                'brand' => 'TP-Link',
                'model_no' => 'Archer C6',
                'description' => 'AC1200 dual-band gigabit Wi-Fi router for remote CCTV access',
                'unit' => 'Nos',
                'cost_price' => 1800,
                'unit_price' => 2800,
                'stock_quantity' => 18,
                'min_stock_alert' => 4,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'TPLINK-OMADA-AP',
                'name' => 'TP-Link Omada Access Point',
                'category' => 'Networking',
                'brand' => 'TP-Link',
                'model_no' => 'EAP225',
                'description' => 'Business AC1350 ceiling-mount Wi-Fi access point with seamless roaming',
                'unit' => 'Nos',
                'cost_price' => 4000,
                'unit_price' => 6200,
                'stock_quantity' => 10,
                'min_stock_alert' => 2,
                'hsn_code' => '85176290',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'CABLE-CAT6',
                'name' => 'CAT6 Cable',
                'category' => 'Cable',
                'brand' => 'Polycab / D-Link',
                'model_no' => 'CAT6-UTP-COPPER',
                'description' => '100% pure copper CAT6 high speed network cable (305m roll)',
                'unit' => 'Mtr',
                'cost_price' => 12,
                'unit_price' => 20,
                'stock_quantity' => 3500,
                'min_stock_alert' => 500,
                'hsn_code' => '85444999',
                'tax_rate' => 18,
                'default_warranty_months' => 60,
            ],
            [
                'sku' => 'CABLE-COAX-3-1',
                'name' => 'Coaxial CCTV Cable',
                'category' => 'Cable',
                'brand' => 'Finolex',
                'model_no' => 'RG59-3+1',
                'description' => '3+1 solid copper coaxial cable for analog CCTV camera installation',
                'unit' => 'Mtr',
                'cost_price' => 15,
                'unit_price' => 25,
                'stock_quantity' => 2000,
                'min_stock_alert' => 300,
                'hsn_code' => '85444999',
                'tax_rate' => 18,
                'default_warranty_months' => 60,
            ],
            [
                'sku' => 'RJ45-CONNECTOR',
                'name' => 'RJ45 Connector',
                'category' => 'Accessories',
                'brand' => 'D-Link',
                'model_no' => 'RJ45-CAT6-GOLD',
                'description' => 'Gold plated RJ45 pass-through connector and boot cap',
                'unit' => 'Nos',
                'cost_price' => 5,
                'unit_price' => 15,
                'stock_quantity' => 850,
                'min_stock_alert' => 100,
                'hsn_code' => '85366990',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'CCTV-JBOX',
                'name' => 'CCTV Junction Box',
                'category' => 'Accessories',
                'brand' => 'Generic Pro',
                'model_no' => 'JB-WP-4X4',
                'description' => 'Weatherproof IP65 camera mounting and cable termination junction box',
                'unit' => 'Nos',
                'cost_price' => 75,
                'unit_price' => 180,
                'stock_quantity' => 180,
                'min_stock_alert' => 30,
                'hsn_code' => '85381010',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'CCTV-PSU-12V',
                'name' => '12V CCTV Power Supply',
                'category' => 'Power',
                'brand' => 'CP PLUS',
                'model_no' => 'CP-DPS-MD100-12D',
                'description' => '12V DC 8-channel SMPS power supply with surge protection',
                'unit' => 'Nos',
                'cost_price' => 360,
                'unit_price' => 650,
                'stock_quantity' => 25,
                'min_stock_alert' => 5,
                'hsn_code' => '85044090',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'UPS-1KVA',
                'name' => '1 kVA UPS',
                'category' => 'Power',
                'brand' => 'APC / Microtek',
                'model_no' => 'APC-BX1100C-IN',
                'description' => 'Line-interactive 1100VA UPS backup power with AVR for DVR/NVR setup',
                'unit' => 'Nos',
                'cost_price' => 3600,
                'unit_price' => 5200,
                'stock_quantity' => 14,
                'min_stock_alert' => 3,
                'hsn_code' => '85044090',
                'tax_rate' => 18,
                'default_warranty_months' => 24,
            ],
            [
                'sku' => 'RACK-WALL-6U',
                'name' => 'Wall Mount Network Rack 6U',
                'category' => 'Racks',
                'brand' => 'Valrack / Netrack',
                'model_no' => 'RACK-6U-550MM',
                'description' => '6U 550mm depth wall mount rack with glass front door and fan',
                'unit' => 'Nos',
                'cost_price' => 2300,
                'unit_price' => 3800,
                'stock_quantity' => 12,
                'min_stock_alert' => 3,
                'hsn_code' => '94032090',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'RACK-WALL-9U',
                'name' => 'Wall Mount Network Rack 9U',
                'category' => 'Racks',
                'brand' => 'Valrack / Netrack',
                'model_no' => 'RACK-9U-600MM',
                'description' => '9U wall mount equipment rack with cable manager and PDU',
                'unit' => 'Nos',
                'cost_price' => 3200,
                'unit_price' => 5200,
                'stock_quantity' => 8,
                'min_stock_alert' => 2,
                'hsn_code' => '94032090',
                'tax_rate' => 18,
                'default_warranty_months' => 36,
            ],
            [
                'sku' => 'SERVICE-CAM-INSTALL',
                'name' => 'CCTV Camera Installation Charge',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'LABOR-PER-CAM',
                'description' => 'Professional camera mounting, cable connection, angle calibration and testing',
                'unit' => 'Nos',
                'cost_price' => 150,
                'unit_price' => 500,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998719',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'SERVICE-CCTV-CONFIG',
                'name' => 'CCTV Installation and Configuration',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'LABOR-NVR-SETUP',
                'description' => 'Recorder setup, hard disk initialization, IP configuration and mobile app link',
                'unit' => 'Job',
                'cost_price' => 800,
                'unit_price' => 3500,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998719',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'SERVICE-REMOTE-VIEW',
                'name' => 'Remote Mobile Viewing Setup',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'SERVICE-MOBILE-APP',
                'description' => 'DVR/NVR cloud internet configuration and multi-device app setup',
                'unit' => 'Job',
                'cost_price' => 200,
                'unit_price' => 1000,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998719',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'SERVICE-RACK-INSTALL',
                'name' => 'Network Rack Installation',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'LABOR-RACK-MOUNT',
                'description' => 'Wall-mount rack anchor installation and structured cable termination',
                'unit' => 'Job',
                'cost_price' => 600,
                'unit_price' => 2500,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998719',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
            [
                'sku' => 'SERVICE-SITE-SURVEY',
                'name' => 'CCTV Site Survey',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'SERVICE-SURVEY',
                'description' => 'Engineer site visit, coverage area audit, cable route mapping & proposal design',
                'unit' => 'Job',
                'cost_price' => 250,
                'unit_price' => 1000,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998319',
                'tax_rate' => 18,
                'default_warranty_months' => 0,
            ],
            [
                'sku' => 'SERVICE-AMC',
                'name' => 'Annual Maintenance Contract',
                'category' => 'Service',
                'brand' => 'In-House Service',
                'model_no' => 'SERVICE-AMC-YEAR',
                'description' => 'One-year CCTV preventive maintenance, quarterly cleaning & priority breakdown SLA',
                'unit' => 'Job',
                'cost_price' => 1500,
                'unit_price' => 6000,
                'stock_quantity' => 9999,
                'min_stock_alert' => 0,
                'hsn_code' => '998719',
                'tax_rate' => 18,
                'default_warranty_months' => 12,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                [
                    'name' => $product['name'],
                    'category' => $product['category'] ?? 'General',
                    'brand' => $product['brand'] ?? 'Hikvision',
                    'model_no' => $product['model_no'] ?? null,
                    'description' => $product['description'],
                    'unit' => $product['unit'],
                    'cost_price' => $product['cost_price'],
                    'unit_price' => $product['unit_price'],
                    'stock_quantity' => $product['stock_quantity'] ?? 10,
                    'min_stock_alert' => $product['min_stock_alert'] ?? 2,
                    'hsn_code' => $product['hsn_code'] ?? '85258900',
                    'tax_rate' => $product['tax_rate'] ?? 18.00,
                    'default_warranty_months' => $product['default_warranty_months'] ?? 24,
                    'is_active' => true,
                ]
            );
        }
    }
}